language: php
php:
    - 7.1
    - 7.2
    - 7.3

matrix:
    fast_finish: true

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
        - vendor

before_script:
    # Install Nette Tester
    - phpenv config-rm xdebug.ini || true
    - travis_retry composer update --no-interaction --prefer-source

script:
    - ./vendor/bin/tester ./tests/test.php

after_failure:
    # Print *.actual content & log content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
    - for i in $(find tests -name \*.log); do echo "--- $i"; cat $i; echo; echo; done
